"""Keywords, patterns, and page elements used in message analysis."""

import re

WORD_PATTERN = re.compile(r"\b[\wÀ-ÿ]+(?:[-'][\wÀ-ÿ]+)*\b")
SENTENCE_PATTERN = re.compile(r"(?<=[.!?])\s+")

MIN_WORDS = 50
MIN_LEAD_WORDS = 6
LEAD_MAX_CHARS = 300

# A generic desktop Chrome UA. Some sites serve a stripped-down or blocked
# page to the default Playwright UA, which can look like "0 words extracted".
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

# Rendering / retry tuning. A page gets up to MAX_ATTEMPTS tries: the first
# waits only for "domcontentloaded", later ones wait for full "load", which
# tends to fix single-page apps that render their content after that event.
NAV_TIMEOUT_MS = 60_000
IDLE_TIMEOUT_MS = 12_000
POST_LOAD_WAIT_MS = 2_500
MAX_ATTEMPTS = 3
RETRY_DELAY_MS = 3_000

CONTENT_SELECTORS = (
    "main",
    "article",
    '[role="main"]',
)

REMOVE_SELECTORS = (
    "script",
    "style",
    "noscript",
    "template",
    "svg",
    "canvas",
    "iframe",
    "nav",
    '[role="navigation"]',
)

REMOVE_UNLESS_CONTENT_SELECTORS = (
    "header",
    "footer",
    "form",
    '[class*="cookie"]',
    '[id*="cookie"]',
    '[class*="consent"]',
    '[id*="consent"]',
    '[class*="modal"]',
    '[class*="overlay"]',
    '[class*="chatbot"]',
    '[class*="chat-bot"]',
)

COOKIE_BUTTON_TEXTS = (
    "only necessary",
    "necessary only",
    "essential only",
    "reject",
    "decline",
    "refuse",
    "refuser",
    "uniquement les cookies nécessaires",
    "alleen noodzakelijke",
    "alleen functionele",
    "weiger",
    "accept all",
    "allow all",
    "accept",
    "agree",
    "tout accepter",
    "accepter",
    "alles accepteren",
    "alle cookies accepteren",
    "accepteer",
    "akkoord",
)

BOILERPLATE_MARKERS = (
    "©",
    "all rights reserved",
    "tous droits",
    "alle rechten",
    "fsma",
    "ondernemingsnummer",
    "numéro d'entreprise",
    "rpr",
    "rpm",
    "btw be",
    "tva be",
    "cookie",
    "privacy",
    "vie privée",
    "disclaimer",
    "onder toezicht",
    "sous le contrôle",
)

# Density ranges: (score 1 at or below, score 5 at or above).
# Values are hits per 100 words. Starting guesses: tune them using the
# "raw_scores" saved in the output JSON.
SCALE_RANGES = {
    "tone_formality": (0, 5),
    "tone_friendliness": (0, 3),
    "tone_persuasiveness": (0, 3),
    "emotional_vs_rational": (0, 12),
    "customer_vs_product_focus": (-4, 4),
    "feature_vs_benefit_focus": (-2, 3),
}

FORMAL_MARKERS = (
    "terms",
    "conditions",
    "agreement",
    "contract",
    "eligibility",
    "shall",
    "must",
    "pursuant",
    "liable",
    "regulation",
    "compliance",
    "contrat",
    "convention",
    "éligibilité",
    "doit",
    "obligatoire",
    "conformément",
    "réglementation",
    "responsabilité",
    "conformité",
    "voorwaarden",
    "overeenkomst",
    "geschiktheid",
    "moet",
    "verplicht",
    "overeenkomstig",
    "reglement",
    "aansprakelijk",
    "conformiteit",
)

FRIENDLY_MARKERS = (
    "welcome",
    "discover",
    "help",
    "easy",
    "simple",
    "together",
    "enjoy",
    "thanks",
    "happy to",
    "bienvenue",
    "découvrez",
    "aide",
    "facile",
    "ensemble",
    "profitez",
    "merci",
    "avec plaisir",
    "welkom",
    "ontdek",
    "eenvoudig",
    "makkelijk",
    "gemakkelijk",
    "samen",
    "geniet",
    "bedankt",
    "met plezier",
)

PERSUASIVE_MARKERS = (
    "discover",
    "choose",
    "get started",
    "apply",
    "request",
    "find out",
    "contact us",
    "sign up",
    "subscribe",
    "open an account",
    "simulate",
    "limited",
    "découvrez",
    "choisissez",
    "commencez",
    "demandez",
    "souscrivez",
    "ouvrez",
    "contactez",
    "en savoir plus",
    "simulez",
    "calculez",
    "limitée",
    "ontdek",
    "kies",
    "start",
    "aanvragen",
    "bereken",
    "contacteer",
    "neem contact",
    "schrijf in",
    "open een",
    "meer weten",
    "simuleer",
    "beperkt",
)

EMOTIONAL_MARKERS = (
    "feel",
    "freedom",
    "peace of mind",
    "dream",
    "happy",
    "enjoy",
    "comfort",
    "worry-free",
    "confidence",
    "trust",
    "love",
    "ressent",
    "liberté",
    "tranquillité",
    "sérénité",
    "rêve",
    "heureux",
    "profitez",
    "confort",
    "confiance",
    "sans souci",
    "aimez",
    "gevoel",
    "vrijheid",
    "gerust",
    "gemoedsrust",
    "droom",
    "gelukkig",
    "geniet",
    "vertrouwen",
    "zorgeloos",
    "houd van",
)

CUSTOMER_MARKERS = (
    "you",
    "your",
    "customer",
    "need",
    "want",
    "goal",
    "family",
    "yourself",
    "vous",
    "votre",
    "vos",
    "client",
    "besoin",
    "souhait",
    "envie",
    "objectif",
    "famille",
    "projet",
    "u",
    "je",
    "jij",
    "jouw",
    "uw",
    "klant",
    "behoefte",
    "wens",
    "doel",
    "gezin",
    "project",
)

PRODUCT_MARKERS = (
    "account",
    "loan",
    "insurance",
    "savings",
    "mortgage",
    "card",
    "credit",
    "investment",
    "product",
    "pension",
    "deposit",
    "compte",
    "prêt",
    "crédit",
    "assurance",
    "épargne",
    "hypothécaire",
    "carte",
    "placement",
    "investissement",
    "produit",
    "dépôt",
    "rekening",
    "lening",
    "krediet",
    "verzekering",
    "sparen",
    "spaar",
    "hypotheek",
    "kaart",
    "beleggen",
    "belegging",
    "pensioen",
    "deposito",
)

FEATURE_MARKERS = (
    "includes",
    "offers",
    "provides",
    "available",
    "option",
    "condition",
    "rate",
    "term",
    "coverage",
    "limit",
    "minimum",
    "maximum",
    "duration",
    "eligible",
    "comprend",
    "inclut",
    "propose",
    "disponible",
    "taux",
    "durée",
    "couverture",
    "plafond",
    "éligible",
    "bevat",
    "omvat",
    "biedt",
    "beschikbaar",
    "optie",
    "voorwaarde",
    "rentevoet",
    "looptijd",
    "dekking",
    "waarborg",
    "limiet",
    "duur",
    "in aanmerking",
)

BENEFIT_MARKERS = (
    "benefit",
    "save",
    "protect",
    "convenient",
    "flexible",
    "secure",
    "advantage",
    "reward",
    "guarantee",
    "safe",
    "avantage",
    "bénéfice",
    "économis",
    "économie",
    "protég",
    "protection",
    "pratique",
    "sécuris",
    "sûr",
    "garantie",
    "gain",
    "voordeel",
    "bespaar",
    "besparing",
    "bescherm",
    "bescherming",
    "praktisch",
    "flexibel",
    "veilig",
    "zekerheid",
    "gemak",
    "rendement",
)

LIFESTYLE_MARKERS = (
    "life",
    "future",
    "family",
    "home",
    "travel",
    "mobility",
    "lifestyle",
    "retirement",
    "holiday",
    "children",
    "vie",
    "avenir",
    "famille",
    "maison",
    "logement",
    "voyage",
    "mobilité",
    "retraite",
    "vacances",
    "enfants",
    "leven",
    "toekomst",
    "gezin",
    "familie",
    "thuis",
    "wonen",
    "woning",
    "reizen",
    "mobiliteit",
    "pensioen",
    "vakantie",
    "kinderen",
)

PRICE_MARKERS = (
    "price",
    "cost",
    "fees",
    "monthly",
    "per month",
    "interest",
    "premium",
    "free of charge",
    "annual",
    "prix",
    "coût",
    "frais",
    "tarif",
    "mensuel",
    "par mois",
    "prime",
    "gratuit",
    "intérêt",
    "annuel",
    "prijs",
    "kost",
    "tarief",
    "maandelijks",
    "per maand",
    "premie",
    "gratis",
    "rente",
    "vergoeding",
    "jaarlijks",
)
